### ISSUE TITLE
Blog posts are inaccessible

### ISSUE THREAD

**Issue by mtlynch** [ButterCMS/gridsome-starter-buttercms-old#7]
The starter contains an index of blog posts, but the blog posts are not clickable:

![butter-click](https://user-images.githubusercontent.com/7783288/87235872-2e32dd80-c3af-11ea-839c-3bb2408ee1ba.gif)

**Comment by jakelumetta** [comment]
@BobWalsh Can you take a look at this one please?

**Comment by jonalecpalustre** [comment]
@mtlynch I've also fixed this now on the latest commit - https://github.com/ButterCMS/gridsome-starter-buttercms/commit/ec70b3ca820130b943f8c9a89757cf2f0f57341e

**Comment by mtlynch** [comment]
Cool, when do you expect to merge in the changes into master so readers can test this on the demo site?

**Comment by jonalecpalustre** [comment]
@mtlynch This has been merged to master now. Thanks!
