### ISSUE TITLE
Remove extraneous files

### ISSUE THREAD

**Issue by mtlynch** [ButterCMS/gridsome-starter-buttercms-old#8]
This repo contains lots of extraneous `README.md` that came with the Gridsome boilerplate project. These shouldn't be part of the starter.

There's also a stray `.DS_STORE` file at the repo root that shouldn't be in source control.

**Comment by jakelumetta** [comment]
@BobWalsh Can you take a look at this one please?

**Comment by jonalecpalustre** [comment]
@mtlynch This has been updated as well. Could you please check - https://github.com/ButterCMS/gridsome-starter-buttercms/

Thanks!

**Comment by mtlynch** [comment]
The `.DS_STORE` file is gone, but the extraneous READMEs are still there. Also, it's helpful if you point to a particular commit or PR that addresses the issue rather than the whole repo.

**Comment by jonalecpalustre** [comment]
@mtlynch Found all those READMEs and deleted them. Please check it here - https://github.com/ButterCMS/gridsome-starter-buttercms/commit/ec70b3ca820130b943f8c9a89757cf2f0f57341e
